package com.abhiroop.chatbackend.exception;

public enum ErrorCode {
    VALIDATION_FAILED("VALIDATION_FAILED"),
    CONSTRAINT_VALIDATION_FAILED("CONSTRAINT_VALIDATION_FAILED"),
    DATA_INTEGRITY_VALIDATION_FAILED("DATA_INTEGRITY_VALIDATION_FAILED"),
    EMAIL_ALREADY_PRESENT("EMAIL_ALREADY_PRESENT"),
    PASSWORD_VALIDATION_FAILED("PASSWORD_VALIDATION_FAILED"),
    USERNAME_GENERATION_FAILED("USERNAME_GENERATION_FAILED"),
    UNHANDLED_EXCEPTION_OCCURRED("UNHANDLED_EXCEPTION_OCCURRED"),
    UNAUTHORIZED_USER("UNAUTHORIZED_USER_FOUND"),
    JWT_VALIDATION_FAILED("JWT_VALIDATION_FAILED"),
    CHAT_ROOM_NOT_FOUND("CHAT_ROOM_NOT_FOUND"),
    CHAT_ROOM_EDIT_NOT_AUTHORIZED("CHAT_ROOM_EDIT_NOT_AUTHORIZED"),
    INVALID_MESSAGE_TYPE("INVALID_MESSAGE_TYPE");


    private final String errorString;

    ErrorCode(String errorString) {
        this.errorString = errorString;
    }

    @Override
    public String toString() {
        return errorString;
    }
}
