name: Trigger auto deployment for chatappbackend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      [ main ]
    paths:
      - '**'
      - '.github/workflows/chatappbackend-AutoDeployTrigger-86d58de7-e765-4c3b-a674-7621b771d875.yml'

  # Allow manual trigger 
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CHATAPPBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CHATAPPBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CHATAPPBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: ./Dockerfile
          targetLabel: chatAppBackend
          acrName: chatappbackendcontainerregistry
          containerAppName: chatappbackend
          resourceGroup: chatappWebsite
          imageToBuild: chatappbackendcontainerregistry-fec9grddbdbzf5an.azurecr.io/chatappbackend:${{ github.sha }}